name: Build and Publish Extension
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: astral-sh/setup-uv@v3

      - name: Update Version Numbers
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
          if ! [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format: $VERSION. Expected format: X.Y.Z"
            exit 1
          fi
          for file in client/package.json client/package-lock.json server/server.py; do
            sed -i "s/0\.0\.0+dynamic-from-tags/$VERSION/" "$file"
          done
      
      - name: Install Dependencies
        run: cd client && npm ci
      
      - name: Compile and Create VSIX
        run: |
          cd client
          npm install
          npm install -g vsce
          npm run compile 
          npm run webpack 
          npm run vscepack
      
      - name: Upload VSIX as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: client/*.vsix
      
      - name: Publish to VS Code Marketplace
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd client
          vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_PRIVATE_ACCESS_TOKEN }}